### PR TITLE
Up to date SSL support 

### PR DESCRIPTION
**Pull request by saleyn**
This is an updated version of this pull request https://github.com/facebook/scribe/pull/44 that adds SSL support.

### CODE REVIEW

**Comment by saleyn** [comment]
The latest commit also adds support of Unix Domain Sockets. I decided not to rebase this commit on the master since both UDS and SSL implementations are complimentary and involve overlapped changes.

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Scribe externally for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Comment by saleyn** [comment]
What happens with the commits in the pull requests? Do they all get ignored?

**Comment by jamesgpearce** [comment]
There is no-one maintaining this repo actively, but I'll ping someone on the old team to see if they can accept this.

**Pull request closed without merging**
