### PR TITLE
Add support for SSL and Thrift 0.7.0

### PR DESCRIPTION
**Pull request by ghost**
This patch, branched from Scribe 2.2, adds support for SSL between Scribe servers (new in Thrift 0.7.0). This allows logs to be securely transmitted from a datacenter to a central location. Example configuration files are included, along with a helper script to generate a self-signed certificate pair.

### CODE REVIEW

**Comment by forsberg** [comment]
I'm having some trouble getting this to compile, it fails with a link error for SSL functions, which I think is due to it linking in thrift libraries statically.

I solved my immediate problem by adding this patch:

```
diff --git a/configure.ac b/configure.ac
index b13a56b..32a1ecd 100644
--- a/configure.ac
+++ b/configure.ac
@@ -64,6 +64,8 @@ AX_BOOST_BASE([1.36])
 AX_BOOST_SYSTEM
 AX_BOOST_FILESYSTEM

+AC_CHECK_LIB(ssl, SSL_ctrl)
+
 # Generates Makefile from Makefile.am. Modify when new subdirs are added.
 # Change Makefile.am also to add subdirectly.
 AC_CONFIG_FILES(Makefile src/Makefile lib/py/Makefile)
```

..which makes it add -lssl.

Not sure this is the _right_ solution though.

**Comment by qualtrics** [comment]
I think adding the explicit dependency is a good idea. Loading the Thrift libraries dynamically should not be a requirement.

**Comment by saleyn** [comment]
Can you bring this patch up to date to the current HEAD?

Never mind, see my patch: https://github.com/facebook/scribe/pull/78

**Comment by jamesgpearce** [comment]
Facebook has not maintained or supported Scribe externally for some time, and we are closing its old and outstanding pull requests.

Many, many thanks for your support of the project. If you have any further questions, please don't hesitate to let me know.

**Pull request closed without merging**
